name: portfolio
description: A modern portfolio website built with Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.2
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/back.jpg
    - assets/images/mee.png
    - assets/images/back.png
    - assets/images/me.png
    - assets/images/edit.jpg
    - assets/images/ORG.jpg
    - assets/images/2.png
    - assets/images/id.png
    - assets/images/gr.jpg
    - assets/images/bl.jpg
